### PR TITLE
vue-template-compiler as a peer dependency

### PR DESCRIPTION
**Pull request by oligot**
`vue-template-compiler` is now a peer dependency instead of a direct dependency.
This allows the user to pin `vue-template-compiler` to a specific version instead of relying on the implicit upgrades from a semver caret range.

Without this change, updating Vue.js to version 2.4.2 can result in
errors like this:

Vue packages version mismatch:

- vue@2.4.2
- vue-template-compiler@2.4.1

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

This was first reported in [vue-loader](https://github.com/vuejs/vue-loader/issues/470) and later [fixed in version 10.0.0](https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#vue-loader1000).

There is also [an open issue on vueify](https://github.com/vuejs/vueify/issues/159) but it's not currently fixed.

### CODE REVIEW

**Comment by znck** [comment]
Peer dependencies are deprecated from npm v3.x

**Comment by oligot** [comment]
According to the [npm 3.0.0 release doc](https://github.com/npm/npm/releases/tag/v3.0.0), peerDependencies no longer cause _anything_ to be implicitly installed but the notion of peer dependencies is still there and clearly not deprecated.

> Instead, npm will now warn if a packages peerDependencies are missing, but it's up to the consumer of the module (i.e. you) to ensure the peers get installed / are included in package.json as direct dependencies or devDependencies of your package.

Could this PR be reopened as I still get errors when upgrading to Vue 2.4.3 this time ?

**Comment by znck** [comment]
Please check for failing tests.

**Comment by oligot** [comment]
Tests now work when run locally but they fail on Circle CI and I don't really know why (this doesn't seem to be related to this PR)...

Can you have a look and see what's wrong with Circle CI ?

**Comment by oligot** [comment]
Thanks  :v:

**Comment by oligot** [comment]
I just noticed that you reverted the changes in 42082ff2e12ae994f65cf937a47c983e997b2d3b (vue-template-compiler is now a dependency instead of a peerDependency).
Can you explain why you reverted these changes ?

**Comment by znck** [comment]
That was a fix failing build on CI. `vue-template-compiler` should be in devDependencies and peerDependencies.

**Comment by znck** [comment]
I'll patch it today. ,

**Comment by oligot** [comment]
Ok thanks !

**Pull request merged**
