### PR TITLE
Add compileOptions

### PR DESCRIPTION
**Pull request by fenduru**
Changes proposed in this pull request:
- Adds the ability for users to pass template compiler options

/ping @znck

### CODE REVIEW

**Comment by znck** [comment]
Please update docs to reflect the change.

**Comment by fenduru** [comment]
@znck How are the docs managed? Should I just modify `docs/en/2.3/README.md` directly?

**Comment by znck** [comment]
Yes!

**Comment by fenduru** [comment]
Added docs

**Pull request merged**
