### PR TITLE
support postcss

### LINKED ISSUE #102: Autoprefixer support
Currently, only cssModules is exposed in the configuration, making it impossible to add things like autoprefixer (since that's done at a higher level config object).

### PR DESCRIPTION
**Pull request by sunnylost**
Fixes #102 #118 #122 .

Changes proposed in this pull request:
- support postcss

Previously, "module" and "scoped" cannot be set at the same time, only "module" has effect, this PR fix this.

I will try to solve css sourcemap issue, haven't got a clue yet.

/ping @znck

### CODE REVIEW

**Comment by jonataswalker** [comment]
Waiting for this feature. Thanks @sunnylost

**Comment by znck** [comment]
Releasing next version on 23rd September.

**Comment by nblackburn** [comment]
@znck You sure about that? 😆

**Comment by znck** [comment]
Caught up with something. I'll publish a release ASAP.

**Pull request merged**
