### PR TITLE
fix: generate compiler per component to pass information about scopeId

### LINKED ISSUE #321: No scoped attribute in children elements with scss
### Version
5.1.1

### Steps to reproduce
- Use https://github.com/team-innovation/vue-sfc-rollup to make a sample
- Use scoped scss

### What is expected?
All elements have scope identifier attribute.

### What is actually happening?
Only root element have scope identifier.

---
Im working with nuxt and importing my module to test it. But developing "library" independently.

### PR DESCRIPTION
**Pull request by przemkow**
Fixes #321

Changes proposed in this pull request:
- Generate compiler instance per component so component `scopeId` can be passed as a variable to generate correctly optimised SSR code.

I tried to add tests for that but it seems that currently tests enviroment supports only `iife` build.

/ping @znck

### CODE REVIEW

**Comment by znck** [comment]
It looks good but I need some time to properly review the code (😞 as CI is broken).

**Comment by przemkow** [comment]
yea I noticed that. No worries @znck, take you time :) if you notice that something needs to be changed let me know :)

**Comment by hjkcai** [comment]
How is it going here? I have the same problem and I really need this fix. Thanks @znck @przemkow 

BTW in the fix code, is it fine to create the compiler multiple times? I am not sure about it. My fix might be simpler:

```ts
if (descriptor.template) {
  const hasScoped = descriptor.styles.some(s => !!s.scoped);

  // magic!
  Object.assign(compiler.template.compilerOptions, { scopeId: hasScoped ? scopeId : undefined });

  // ...
}
```

**Comment by przemkow** [comment]
@hjkcai Thanks for that suggestion! To be honest I was thinking about something similar but I wasn't sure if mutating the compilerOptions will not create any side-effects. 
I noticed that `vue-loader` seems to create a separate instance of [templateLoader](https://github.com/vuejs/vue-loader/blob/master/lib/loaders/templateLoader.js) per file so I tried to implement a similar approach with as small modifications as possible. 
If you have some time @znck let us know what do you think about that :) If any modifications are required I will try to update this PR as soon as possible.

**Comment by znck** [comment]
Transform function is async and mutation could potentially produce wrong results. 

P.S. I’ll merge it today. Apologies for the delay.

**Comment by hjkcai** [comment]
Good job @znck @przemkow

Thanks a lot

**Pull request merged**
