### PR TITLE
Typescript support

### LINKED ISSUE #99: Support TypeScript in <script> tags
~~This is not a bug, but a feature request. If this is not the correct place then just redirect me and close this issue. :)~~

Given that rollup already supports TypeScript via one of two plugins, it would be nice for this plugin to allow something along the lines of:
```
<script lang="ts">
// typescript Vue component here.
</script>
```

### PR DESCRIPTION
**Pull request by Jack-Works**
Fixes #99 .

Now we can use 
```html
<script lang="ts">
    interface ITypescriptCodeHere {}
</script>
```

And add support to inject code like this
```typescript
import App from './app.ts'
export default App
```
this will generate
```
var __$App= Object.assign(App, {
    /*  renders, _scopeIDs and other stuff will injected to here */
})
__$App.prototype = App.prototype
export default __$App
```

/ping @znck

### CODE REVIEW

**Comment by Jack-Works** [comment]
Hmm, I fix the eslint problem, but I get stuck in the unit test.
They are 1) should rollup coffee.vue
    2) should rollup scoped-css-with-no-auto-style.vue
    3) should rollup scoped-css.vue
See details in CI result.
I have no idea about what is messed up.

Any help? Thanks. @znck

**Comment by znck** [comment]
Thanks a lot @Jack-Works. 

I would review it later this week.

**Comment by Jack-Works** [comment]
@znck Em.. Hello?

**Comment by znck** [comment]
Sorry! I was caught up with some things. I'd try to this week.

**Comment by znck** [comment]
Hey @Jack-Works 

Apologies for the delay. Tests all green now. Please add covering tests for your change.

Thanks.

**Comment by Jack-Works** [comment]
@znck All tests passed I think...

**Pull request merged**
